FROM alpine:3.15.0

# install prerequisites
# https://wordpress.com/support/php-environment/
RUN apk update && \
  	apk add --no-cache \
	curl \
	less \
	mariadb-client \
	php8 \
	php8-common \
	php8-session \
	php8-iconv \
	php8-json \
	php8-gd \
	php8-curl \
	php8-xml \
	php8-mysqli \
	php8-imap \
	php8-pdo \
	php8-pdo_mysql \
	php8-soap \
	php8-posix \
	php8-gettext \
	php8-ldap \
	php8-ctype \
	php8-dom \
	php8-simplexml

#RUN the adminer part, create html directory, move the adminer directory and add user

RUN \
	curl -L -O https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php && \
	mkdir -p /var/www/html && \
	mv ./adminer-4.8.1.php /var/www/html/index.php && \
	adduser -u 82 -D -S -G www-data www-data

WORKDIR /var/www/html

EXPOSE 8080
STOPSIGNAL SIGQUIT

CMD ["php8", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]

# minimal virsion

# FROM debian:bullseye

# # Install PHP + extensions + mariadb client
# RUN apt-get update && apt-get install -y \
#     php php-cli php-mysql curl less mariadb-client \
#     && rm -rf /var/lib/apt/lists/*

# # Working directory for Adminer
# WORKDIR /var/www/html

# # Download Adminer and set as index.php
# RUN curl -L -o index.php https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php

# # Run as the existing www-data user (UID 33 in Debian)
# USER www-data

# # Document exposed port
# EXPOSE 8080

# # Start PHP built-in server
# CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
