FROM debian:bullseye

RUN		apt update -y && apt install mariadb-server -y \

COPY	conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf

COPY	tools/init_db.sh	/

RUN 	chmod 755 init_db.sh

CMD ["bash", "init_db.sh"]