FROM	debian:bullseye

RUN		apt update -y && \
			apt install  -y nginx openssl && \
			mkdir -p /etc/nginx/ssl

RUN 	openssl req -x509 -nodes \
			-keyout /etc/nginx/ssl/inception.key \
			-out /etc/nginx/ssl/inception.crt \
			-subj "/C=FR/ST=IDF/L=1337/O=42/OU=42/CN=UserName.42.fr/UID=UserName"
			# -subj "/C=MA/ST=BG/L=1337/O=UM6P/OU=42/CN=ajabri.42.fr/UID=ajabri"

COPY	conf/nginx.conf /etc/nginx/nginx.conf

# EXPOSE	443

CMD		["nginx", "-g", "daemon off;"]