services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_net
  website:
    build: ./requirements/bonus/Website
    container_name: website
    image: website
    restart: always
    ports:
      - "8080:80"
    networks:
      - inception_net
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception_net
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    restart: always
    networks:
      - inception_net
    ports:
      - "6379:6379"

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - inception_net
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_net

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ajabri/data/portainer
      o: bind

  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ajabri/data/wordpress
      o: bind

  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ajabri/data/mariadb
      o: bind

networks:
  inception_net:
    driver: bridge
