services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_net
  website:
    build: ./requirements/bonus/Website
    container_name: website
    restart: always
    ports:
      - "8080:80"
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception_net
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception_net
    ports:
      - "6379:6379"
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - inception_net
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_net
volumes:
  wp_data:
  db_data:
  portainer_data:

networks:
  inception_net:
    driver: bridge
