services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_net
  website:
    build: ./requirements/bonus/Website
    container_name: website
    restart: always
    ports:
      - "8080:80"
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception_net
    ports:
      - "21:21"
      - "21100-21110:21100-21110"

volumes:
  wp_data:
  db_data:

networks:
  inception_net:
    driver: bridge
